apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scopic-software
namePrefix: demo-
images:
  - name: ghcr.io/fauzanelka/bitnami-mysql-backup-sidecar:1
    newTag: '1'
resources:
  - secret/bitnami-mysql-backup-sidecar.yaml
  - ../base