apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - namePrefix.yaml
resources:
  - persistentvolumeclaim/backup-daily.yaml
  - persistentvolumeclaim/backup-monthly.yaml
  - deployment/bitnami-mysql-backup-sidecar.yaml